---
- name: Install zabbix agent on node1 Node
  hosts: node1.example.com
  become: true
  tasks:
    - name: Install repositorio zabbix
      ansible.builtin.yum:
        name: https://repo.zabbix.com/zabbix/6.4/rhel/9/x86_64/zabbix-release-latest.el9.noarch.rpm
        state: present
        disable_gpg_check: true

    - name: Install one specific version of Apache
      ansible.builtin.yum:
        name: zabbix-agent
        state: present


    - name: Template a file to /etc/zabbix/zabbix_agentd.conf
      ansible.builtin.copy:
        src: files/zabbix_agentd.conf
        dest: /etc/zabbix/zabbix_agentd.conf
        owner: root
        group: root
        mode: '0655'


    - name: Enable service zabbix-agent, and not touch the state
      ansible.builtin.service:
        name: zabbix-agent
        enabled: yes
    
    
    - name: Start service zabbix-agent, if not started
      ansible.builtin.service:
        name: zabbix-agent
        state: started


    - name: Template a file to /etc/zabbix/zabbix_agentd.conf
      ansible.builtin.copy:
        src: files/id_rsa
        dest: /home/ec2-user/.ssh/id_rsa
        owner: ec2-user
        group: ec2-user
        mode: '0600'


    - name: Template a file to /etc/zabbix/zabbix_agentd.conf
      ansible.builtin.copy:
        src: files/id_rsa.pub
        dest: /home/ec2-user/.ssh/id_rsa.pub
        owner: ec2-user
        group: ec2-user
        mode: '0600'
