---
- name: Git clone and add files
  hosts: node1.example.com
  tasks:


    - name: Read-write git checkout from github
      ansible.builtin.git:
        repo: git@server.example.com:root/eda-debug.git
        dest: /home/ec2-user/
      ignore_errors: true

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /home/ec2-user/eda-debug/rulebooks
        state: directory
        mode: '0755'
        owner: ec2-user
        group: ec2-user

    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: files/webhook-debug.yml 
        dest: /home/ec2-user/eda-debug/rulebooks/webhook-debug.yml 
        owner: ec2-user
        group: ec2-user
        mode: '0644'

