---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: Say Hello
      condition: event.payload.event_name == "Apache Service is down"
      action:
        run_playbook:
          name: say-what.yml
          extra_vars:
            foo: "{{ event.payload.extra_vars }}"

    - name: Identificado alerta de processo do uc4
      condition: event.payload is regex("ucxj is not running", ignorecase=true)
      action:
        run_playbook:
          name: say-what.yml
