---
- name: Create project gitlab
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:

    - name: 'Install requirements'
      pip:
        name: "gitlab"
      vars:
        ansible_python_interpreter: "/usr/bin/python3"

    - name: 'Install requirements'
      pip:
        name: "python-gitlab"
      vars:
        ansible_python_interpreter: "/usr/bin/python3"


    - name: Create a GitLab Project using a username/password via oauth_token
      community.general.gitlab_project:
        api_url: https://server.example.com/
        api_username: root
        api_password: redhat..123
        name: rh1-aap-extra-vars-eda
        validate_certs: false 
    
    - name: Create a GitLab Project using a username/password via oauth_token
      community.general.gitlab_project:
        api_url: https://server.example.com/
        api_username: root
        api_password: redhat..123
        name: eda-debug
        validate_certs: false

    
    - name: Create a GitLab Project using a username/password via oauth_token
      community.general.gitlab_project:
        api_url: https://server.example.com/
        api_username: root
        api_password: redhat..123
        name: rh1-ansible-eda-vars-zabbix
        validate_certs: false

    - name: "Create GitLab User"
      community.general.gitlab_user:
        api_url: https://server.example.com/
        validate_certs: false
        api_username: root
        api_password: redhat..123
        name: root
        username: root
        password: redhat..123
        email: gitlab_admin_280646@example.com
        sshkey_name: MySSH
        sshkey_file: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCZOuvAqzQEFQfMcAQ9zkNRApU/VfP1RVzYOhgRRPhhstAnapsaWIQr5pSLGSITlULptkahQh+B9PgXzMUojzbuYJLFwWc4Vy+Ytg9MApcPqBS8DkwNeAmHGnwIAC4ZFQMlGt0pg2F5E8lVjvJTN7KJLDizE2WP4V9dDrgIKiVe3a3UsOdqAwqDQLt17/botYP5dtXZRJF8XkX+iFIuJ05LqGTn/nJnUEXchMK/zvpZj5zqHhnTLGD8b1XlnGYI5ocziB8qeNhJgTpAAThOtclXwBZUNIWK2Qm3xy5f6lZ/XilALwOzAFFIu+LeSIb/V6efUbBYLMs+DvaT6ygLX8n4Eceb+ko9XYMJlULHb9mEkhxvmK7FojwQRWcS2RvGroqUxlkYNHSYfsHxdUuisFb4gQ7bhesAVsAu8RcJnj9jqxNAqjzn8/gOfaMYzdxGLJo1X798rQ3iGfXgRv6dneFmmLbS7Vv/vKWlf4UoE/3eg3voLlZCYgVKn84YQX10mQk= lab-user@bastion.example.com
        state: present



