---
- name: Install HTTP port 80 on node1 Node
  hosts: node1.example.com
  become: true
  tasks:
    - name: Install httpd
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Ensure the default Apache port is 80
      ansible.builtin.lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: Listen 80

    - name: Enable service httpd, and not touch the state
      ansible.builtin.service:
        name: httpd
        enabled: yes
    
    
    - name: Start service httpd, if not started
      ansible.builtin.service:
        name: httpd
        state: started


