---
version: 1
build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-c"
  EE_BASE_IMAGE: 'aaphub001.lnx.example.local/ee-supported-rhel8:latest'
  EE_BUILDER_IMAGE: 'aaphub001.lnx.example.local/ansible-builder-rhel8:latest'
ansible_config: 'ansible.cfg'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend: |
    RUN cat /etc/os-release
  append:
    - RUN echo This is a post-install command!
    - RUN curl https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo -o /etc/yum.repos.d/hashicorp.repo
    - RUN microdnf -y install terraform